export const PERSONAL_REQUEST = 'PERSONAL_REQUEST';
export const PERSONAL_QUES_NEWEST = 'PERSONAL_QUES_NEWEST';
export const PERSONAL_QUES_OLDEST = 'PERSONAL_QUES_OLDEST';
export const PERSONAL_ANS_NEWEST = 'PERSONAL_ANS_NEWEST';
export const PERSONAL_ANS_OLDEST = 'PERSONAL_ANS_OLDEST';
export const PERSONAL_ERROR  = 'PERSONAL_ERROR';