export const QUESTION_REQUEST = "QUESTION_REQUEST";
export const QUESTION_EDIT_REQUEST = "EDIT_EDIT_REQUEST";
export const QUESTION_CREATE = "QUESTION_CREATE";
export const QUESTION_ERROR = "QUESTION_ERROR";
export const QUESTION_DELETE = "QUESTION_DELETE";
export const QUESTION_EDIT = "QUESTION_EDIT";