export const QUES_NEWEST = 'QUES_NEWEST';
export const QUES_FEATURED = 'QUES_FEATURED';
export const QUES_UNANSWERED = 'QUES_UNANSWERED';
export const QUES_INTERESTING = 'QUES_INTERESTING';
export const QUES_REQUEST = 'QUES_REQUEST';
export const QUES_ERROR = 'QUES_ERROR';