export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_EDIT_REQUEST = "PROFILE_EDIT_REQUEST";
export const PROFILE_EDIT = "PROFILE_EDIT";
export const PROFILE_EDIT_ERROR = "PROFILE_EDIT_ERROR";
export const PROFILE_ERROR = "PROFILE_ERROR";
